### ISSUE TITLE
The height property does not change on window resize

### ISSUE THREAD

**Issue by intelrug** [jd1378/vue-sticky-element#17]
Hello. Me again. :) Faced with another problem.
When I change the width of the window, the height of the block does not adjust.
The bug is not critical, but still not very nice.

<img src="https://user-images.githubusercontent.com/18365200/203138802-68ed47b0-e023-431e-b554-47dc33c18738.png" height="200">
<img src="https://user-images.githubusercontent.com/18365200/203138943-bb104a96-df04-443a-8855-8b0fc1d74361.png" height="200">

**Comment by jd1378** [comment]
Hi
thanks for reporting
I'll fix it soon

**Comment by jd1378** [comment]
I think [Resize Observer](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) has [good support](https://caniuse.com/resizeobserver). but its not perfect, so I'll setup a listener with that when available, and fallback to window resize event to reset the height.

**Comment by jd1378** [comment]
released in v1.2.5 :)
let me know if theres any issue

**Comment by intelrug** [comment]
Thanks. Works great!
