### ISSUE TITLE
Posted Event Error

### ISSUE THREAD

**Issue by lushangkan** [jd1378/vue-sticky-element#24]
When an element disappears or is displayed, both the events show and stuck are published.

Screen shot (GIF):
![ezgif-1-e41e16ae0b](https://github.com/jd1378/vue-sticky-element/assets/41252325/58b46f76-cd81-4a6a-aa61-a485d5d893d1)

code:
`  <sticky-element :scrollElement="scrolEle" stuckClass="navbar-stuck" showClass="navbar-show" transitionClass="navbar-transition" id="sticky-navbar" @show="console.log('show')" @stuck="console.log('stuck')">
`

**Comment by jd1378** [comment]
I apologize for my unclear documentation
it's because the events are fired with the new value of show or stuck
so you have to check like this: `@show="console.log($event)"`
I'll update readme
