### ISSUE TITLE
[BUG] stickyElement child element reloaded after onMounted

### ISSUE THREAD

**Issue by lushangkan** [jd1378/vue-sticky-element#25]
When using stickyElement to wrap an element, the element will be loaded a second time after onMounted, making the element's ref variable null or the specified element invalid, and the style set in onMounted will be overwritten by the style in the html.

Example code:
```
<sticky-element id="sticky-navbar" >
    <div  ref="appNavbar" id="app-navbar" style="--fg: hsl(var(--b1));">
    // ....
   </div>
</sticky-element>

const appNavbar = ref(null)

onMounted(() => {
   console.log(appNavbar); // print "null"
  // or
  console.log(appNavbar.value?.style) //print "undefined"

  const appNavbar1 = document.getElementById('app-navbar');
  appNavbar1.setAttribute('style', '--fg: hsl(var(--test));');
  
  console.log(appNavbar.getAttribute('style')); // print "--fg: hsl(var(--test));"
  // waiting reload
  console.log(appNavbar.getAttribute('style')); // print "--fg: hsl(var(--b1));"
 // or you can see in the developer tools that the style has changed back to --fg: hsl(var(---b1));
}); 

```

**Comment by jd1378** [comment]
Hi
set your ref and style on "sticky-element" instead and see how that goes :)

**Comment by lushangkan** [comment]
> Hi set your ref and style on "sticky-element" instead and see how that goes :)

The ref is not null in sticky-element, but it is still automatically reloaded and the style set in onMounted is overwritten, while defining the style in the sticky-element's parent tag works fine.

**Comment by jd1378** [comment]
well then I don't see any problem, just do that then.

getting overwritten by vue is normal. vue is the source of truth for rendering, not dom. if you want to persist your changes I suggest checking update lifecycle (https://vuejs.org/api/options-lifecycle.html#beforeupdate)

overall I don't recommend manually manipulating the dom, unless you really really have to and know what you are doing
