### ISSUE TITLE
Issue with Nuxt 2 and Vue 2

### ISSUE THREAD

**Issue by dpetrova** [jd1378/vue-sticky-element#27]
I have an issue with the installation of **vue-sticky-element** in a Nuxt 2 project.
Got errors about:
"export 'cloneVNode' (imported as 'cloneVNode$1') was not found in 'vue'
"export 'h' was not found in 'vue'
"export 'withDirectives' was not found in 'vue'

because I'm using Vue 2

**Comment by jd1378** [comment]
well i'm not sure why, but it's working fine in this example (vue2 with latest vue-sticky-element): https://codesandbox.io/p/sandbox/vue-sticky-element-example-vue2-0cowy?file=%2Fsrc%2FApp.vue

I'll try to setup a nuxt 2 project whenever I have time and check this

**Comment by jd1378** [comment]
well, it seems there's no problem with the component's functionality: 
https://codesandbox.io/p/devbox/nostalgic-currying-wmn2q3

The warnings doesn't matter much in this case, since some imports are only available in vue 3

I don't know how you can suppress the warnings sadly
