### ISSUE TITLE
Plans for Vue 3 support?

### ISSUE THREAD

**Issue by jeffreyvanhees** [jd1378/vue-sticky-element#3]
Hi!

Our website uses your great package for a while now. Now we are in the process of upgrading to Vue 3. However, this is not yet supported. Are there any plans to provide support for Vue 3?

**Comment by jd1378** [comment]
Hi ! 
It's been a while since I made this package and I haven't use vue for a while, since I decided to learn react

but I'll see if I have time to update this package
remind me again in 3 or 4 days by putting another comment in this issue if I didn't update it by then

**Comment by jd1378** [comment]
have you tried to see if it works or does not work with vue 3 ?

**Comment by jd1378** [comment]
I have released 1.2.1 with support for Vue 3 
let me know if theres any problem

**Comment by jd1378** [comment]
there was a small issue in 1.2.1, fixed it in 1.2.2

**Comment by jeffreyvanhees** [comment]
Thanks for your work @jd1378! Works perfectly!
